### ISSUE TITLE
A way to pause when enter break session instead of continuing?

### ISSUE THREAD

**Issue by bruhtus** [jsspencer/pomo#6]
First of all, thank you for making this awesome bash script. A lot of pomodoro script out there is either overkill or doesn't have a pause function.

I want to ask, is there a way to pause when enter the break session instead of keep going? like adding pomo_pause function to other function. I'm still new to bash scripting so I'm not sure where should I add pomo_pause function to other function or maybe I should edit other function instead of adding pomo_pause function. Thank you

**Comment by jsspencer** [comment]
If you use `pomo_msg`, then one option would be to add a `pomo_pause` call directly after it sends a message to start a break.

Another option would be to modify `pomo_stat` to also detect the start of a break, as well as the start of a new block (work+break) and then call `pomo_pause` if a break has been detected. That's probably a bit trickier to get right (especially as you only want it to happen the first time a break is detected).

**Comment by bruhtus** [comment]
> If you use `pomo_msg`, then one option would be to add a `pomo_pause` call directly after it sends a message to start a break.

Is this right? because the break session didn't pause and still continuing (I've also place `pomo_pause` before `send_msg` but still the same)
```sh
    if [[ $(( stat - running - left )) -le 1 ]]; then
        if $work; then
            send_msg "$work_end_msg"
            pomo_pause
        else
            send_msg "$break_end_msg"
        fi
    fi
```

As for `pomo_stat`, I'm not sure how to modify that function. My best bet is to use `pomo_msg`.

**Comment by jsspencer** [comment]
Oh, `pomo` only has second resolution on the timings and treats a time of 0 as belonging to the work block. So this means that the next `pomo_msg` call thinks you're at the end of the work period, and repeats the `if $work` branch. (You can similarly trigger repeated end of work messages with a well-timed `pomo.sh pause` command from the command-line.)

At some point I'll change it to millisecond time resolution but it's fine for my purposes and a limitation of how the file system is used to store timings.

The simplest solution in your case is to sleep for a second before `pomo_pause`, so the time recorded is the first second of the break block rather than the last second of the work block.

**Comment by bruhtus** [comment]
> The simplest solution in your case is to sleep for a second before `pomo_pause`, so the time recorded is the first second of the break block rather than the last second of the work block.

It paused for a moment (and from the prefix, it's seems to be in work session) and then continuing to break session. It didn't fully paused like the using the command `pomo.sh pause`, that's kind of weird. Maybe it has something to do with `pomo_stat`? or maybe I need to change `pomo_clock` or `pomo_status` too?

**Comment by jsspencer** [comment]
```
if $work; then
    send_msg "$work_end_msg"
    # Ensure the time advances into the break block
    sleep 1
    pomo_pause
else
    send_msg "$break_end_msg"
fi
```

seems to work for me. (Having the sleep before the `pomo_pause` behaves like you describe for the reason in my previous message)

**Comment by bruhtus** [comment]
It seems like there's something that i changed that make it didn't work. After i re-downloaded the script, it works now. Thanks!
