### ISSUE TITLE
Add break time option

### ISSUE THREAD

**Issue by log101** [jsspencer/pomo#7]
I've been using pomo for a month I really love it! It is very compact and useful. But I think break times should also be added, this would make the program more productive. There is a env. variable from break time but I couldn't find a way to use that feature.

**Comment by jsspencer** [comment]
You can set the environment variable for the break in your shell to control the break time (e.g. https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-linux if you're using bash). Because pomo is designed to be called repeatedly, having a flag (which would then need to be passed each time) isn't so helpful in my view.

At some point I will add a config file option, or the ability to save the state to the pomo file. Patches are, of course, welcome :)
